project: skigp
program: experiments/precipitation.py
method: grid
parameters:
  experiment_type:
    values: [0, 1]
  data_type:
    value: 6
  framework:
    value: 1
  grid_idx:
    values: [2, 3, 11, 5, 6, 7]
  method:
    values: [1, 2]
  seed:
    values: [1, 23, 67, 971, 23427, 431241, 2423717, 9871]
command:
  - /home/ymohit/anaconda3/envs/fkigp/bin/python
  - ${program}
  - ${args}